{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "app.fullname" . }}
  labels: 
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    'haproxy.router.openshift.io/balance': roundrobin
    'haproxy.router.openshift.io/disable_cookies': 'true'
spec:
  host: {{ .Values.route.host }}
  path: {{ .Values.route.path }}
  port:
    targetPort: {{ .Values.service.port }}-http
  to:
    kind: Service
    name: {{ include "app.fullname" . }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None  
  wildcardPolicy: None
{{- end }}
