env: dev

replicaCount: 1
image:
  repository: quay.io/praveenrachamreddy/kartheek-kumar-reddy/tngb-demo-app
  pullPolicy: Always
  tag: "v4"
service:
  type: ClusterIP
  port: 9090
route:
  enabled: true
  host: tngb-demo-project.apps.ocp4.imss.work
  path: /
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 80
labels:
  component: tngb-demo-app
  deploymentconfig: tngb-demo-app
  group: tatacapital
  project: tngb-demo-app
  provider: s2i
  version: 1.0.0
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 10m
    memory: 256Mi
readinessProbe:
  httpGet:
    scheme: HTTP
    path: /rest/health
    port: 9090
  periodSeconds: 30
  initialDelaySeconds: 30
  successThreshold: 1
  failureThreshold: 3
livenessProbe:
  httpGet:
    scheme: HTTP
    path: /rest/health
    port: 9090
  timeoutSeconds: 1
  periodSeconds: 30
  initialDelaySeconds: 30
  successThreshold: 1
  failureThreshold: 3
nodeSelector: {}
tolerations: []
affinity: {}
